title: Ali Chehrazi
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.Minimal is a theme for GitHub Pages.Minimal is a theme for GitHub Pages.Minimal is a theme for GitHub Pages.Minimal is a theme for GitHub Pages.Minimal is a theme for GitHub Pages.Minimal is a theme for GitHub Pages.Minimal is a theme for GitHub Pages.Minimal is a theme for GitHub Pages.Minimal is a theme for GitHub Pages.Minimal is a theme for GitHub Pages.
Minimal is a theme for GitHub Pages.
google_analytics:
theme: jekyll-theme-minimal
